### ISSUE TITLE
dies when password scalars have utf8 bit set

### ISSUE THREAD

**Issue by dk** [ronsavage/Crypt-PasswdMD5#2]
Hello Ron,

I've bumped in this problem where I have a REST/JSON service that among other requests handles auth requests with Crypt::PasswdMD5 sending login/password directly to the unix_md5_crypt function. One could of course argument that manual argument washing is needed before the call, however OTOH /usr/bin/passwd has no problems with unicode input, assuming utf8.

So I'm thinking that it would be a nice addition so that future users won't get tripwired by unexpected utf8 input from a user, and so I made a pull request #1 that addresses just that

Hopefully that makes sense

Regards,
   Dmitry

**Comment by ronsavage** [comment]
V 1.42 is now on CPAN. Thanx.
